FROM python:3.11.9-alpine3.20

WORKDIR /usr/src/app

COPY ./project1 .

RUN python3 -m pip install django-encrypted-model-fields && adduser -D appuser && chown -R appuser .

EXPOSE 8000

USER appuser

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
