FROM ubuntu:22.04

RUN apt-get update && \ 
apt-get install -y curl && \
curl -sL https://deb.nodesource.com/setup_16.x | bash && \
apt-get install -y nodejs && \
apt-get purge -y --auto-remove curl

WORKDIR /usr/src/app

COPY package* .

RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm run build && npm install -g serve && useradd -m appuser

USER appuser

CMD serve -s -l 5000 build
