FROM node:16.20.2-alpine3.18

WORKDIR /usr/src/app

COPY package* .

RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm run build && npm install -g serve && adduser -D appuser

USER appuser

CMD serve -s -l 5000 build
