FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt install -y nodejs

WORKDIR /usr/src/app

COPY package* .

RUN npm install

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm run build

RUN npm install -g serve

RUN useradd -m appuser

USER appuser

CMD serve -s -l 5000 build
